
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action newAction;
	private global::Gtk.Action newAction1;
	private global::Gtk.Action editAction;
	private global::Gtk.Action deleteAction;
	private global::Gtk.Action newAction2;
	private global::Gtk.Action editActionArticulo;
	private global::Gtk.Action deleteActionArticulo;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action refreshAction1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Notebook notebook2;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Toolbar toolbar3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView treeViewArticulo;
	private global::Gtk.Label lblArticulo;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Toolbar toolbar2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeViewCategoria;
	private global::Gtk.Label lblCategoria;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.newAction1 = new global::Gtk.Action ("newAction1", null, null, "gtk-new");
		w1.Add (this.newAction1, null);
		this.editAction = new global::Gtk.Action ("editAction", null, null, "gtk-edit");
		w1.Add (this.editAction, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", null, null, "gtk-delete");
		w1.Add (this.deleteAction, null);
		this.newAction2 = new global::Gtk.Action ("newAction2", null, null, "gtk-new");
		w1.Add (this.newAction2, null);
		this.editActionArticulo = new global::Gtk.Action ("editActionArticulo", null, null, "gtk-edit");
		w1.Add (this.editActionArticulo, null);
		this.deleteActionArticulo = new global::Gtk.Action ("deleteActionArticulo", null, null, "gtk-delete");
		w1.Add (this.deleteActionArticulo, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.refreshAction1 = new global::Gtk.Action ("refreshAction1", null, null, "gtk-refresh");
		w1.Add (this.refreshAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 1;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar3'><toolitem name='newAction2' action='newAction2'/><toolitem name='editActionArticulo' action='editActionArticulo'/><toolitem name='deleteActionArticulo' action='deleteActionArticulo'/><toolitem name='refreshAction' action='refreshAction'/></toolbar></ui>");
		this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar3")));
		this.toolbar3.Name = "toolbar3";
		this.toolbar3.ShowArrow = false;
		this.vbox4.Add (this.toolbar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.toolbar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeViewArticulo = new global::Gtk.TreeView ();
		this.treeViewArticulo.CanFocus = true;
		this.treeViewArticulo.Name = "treeViewArticulo";
		this.GtkScrolledWindow1.Add (this.treeViewArticulo);
		this.vbox4.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
		w4.Position = 1;
		this.notebook2.Add (this.vbox4);
		// Notebook tab
		this.lblArticulo = new global::Gtk.Label ();
		this.lblArticulo.Name = "lblArticulo";
		this.lblArticulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Articulo");
		this.notebook2.SetTabLabel (this.vbox4, this.lblArticulo);
		this.lblArticulo.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='newAction1' action='newAction1'/><toolitem name='editAction' action='editAction'/><toolitem name='deleteAction' action='deleteAction'/><toolitem name='refreshAction1' action='refreshAction1'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.vbox3.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.toolbar2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeViewCategoria = new global::Gtk.TreeView ();
		this.treeViewCategoria.CanFocus = true;
		this.treeViewCategoria.Name = "treeViewCategoria";
		this.GtkScrolledWindow.Add (this.treeViewCategoria);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
		w8.Position = 1;
		this.notebook2.Add (this.vbox3);
		global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox3]));
		w9.Position = 1;
		// Notebook tab
		this.lblCategoria = new global::Gtk.Label ();
		this.lblCategoria.Name = "lblCategoria";
		this.lblCategoria.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoria");
		this.notebook2.SetTabLabel (this.vbox3, this.lblCategoria);
		this.lblCategoria.ShowAll ();
		this.vbox2.Add (this.notebook2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook2]));
		w10.Position = 0;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 524;
		this.DefaultHeight = 433;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction1.Activated += new global::System.EventHandler (this.OnNewAction1Activated);
		this.editAction.Activated += new global::System.EventHandler (this.OnEditCategoriaActionActivated);
		this.newAction2.Activated += new global::System.EventHandler (this.OnNewAction2Activated);
		this.editActionArticulo.Activated += new global::System.EventHandler (this.OnEditArticuloActionActivated);
		this.deleteActionArticulo.Activated += new global::System.EventHandler (this.OnDeleteArticuloActionActivated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
		this.refreshAction1.Activated += new global::System.EventHandler (this.OnRefreshAction1Activated);
	}
}
