
// This file has been generated by the GUI designer. Do not modify.
namespace PArticulo
{
	public partial class NuevoArticulo
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action addAction;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Toolbar toolbar3;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label lblArticulo;
		private global::Gtk.Entry entryArticulo;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label lblPrecio;
		private global::Gtk.Entry entryPrecio;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label lblCategoria;
		private global::Gtk.Entry entryCategoria;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PArticulo.NuevoArticulo
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
			w1.Add (this.addAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "PArticulo.NuevoArticulo";
			this.Title = global::Mono.Unix.Catalog.GetString ("NuevoArticulo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PArticulo.NuevoArticulo.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar3'><toolitem name='addAction' action='addAction'/></toolbar></ui>");
			this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar3")));
			this.toolbar3.Name = "toolbar3";
			this.toolbar3.ShowArrow = false;
			this.vbox4.Add (this.toolbar3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.toolbar3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblArticulo = new global::Gtk.Label ();
			this.lblArticulo.Name = "lblArticulo";
			this.lblArticulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Articulo: ");
			this.hbox4.Add (this.lblArticulo);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblArticulo]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryArticulo = new global::Gtk.Entry ();
			this.entryArticulo.CanFocus = true;
			this.entryArticulo.Name = "entryArticulo";
			this.entryArticulo.IsEditable = true;
			this.entryArticulo.InvisibleChar = '•';
			this.hbox4.Add (this.entryArticulo);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryArticulo]));
			w4.Position = 1;
			this.vbox5.Add (this.hbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblPrecio = new global::Gtk.Label ();
			this.lblPrecio.Name = "lblPrecio";
			this.lblPrecio.LabelProp = global::Mono.Unix.Catalog.GetString ("Precio: ");
			this.hbox5.Add (this.lblPrecio);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblPrecio]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryPrecio = new global::Gtk.Entry ();
			this.entryPrecio.CanFocus = true;
			this.entryPrecio.Name = "entryPrecio";
			this.entryPrecio.IsEditable = true;
			this.entryPrecio.InvisibleChar = '•';
			this.hbox5.Add (this.entryPrecio);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entryPrecio]));
			w7.Position = 1;
			this.vbox5.Add (this.hbox5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox5]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblCategoria = new global::Gtk.Label ();
			this.lblCategoria.Name = "lblCategoria";
			this.lblCategoria.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoria: ");
			this.hbox6.Add (this.lblCategoria);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblCategoria]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryCategoria = new global::Gtk.Entry ();
			this.entryCategoria.CanFocus = true;
			this.entryCategoria.Name = "entryCategoria";
			this.entryCategoria.IsEditable = true;
			this.entryCategoria.InvisibleChar = '•';
			this.hbox6.Add (this.entryCategoria);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entryCategoria]));
			w10.Position = 1;
			this.vbox5.Add (this.hbox6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox6]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox5]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
